#!/bin/sh

# load the configuration information
. /etc/rc.d/rc.conf

mode=${1:-start}
if [ $mode = "start" ]
then
    services=$cfg_services
else
    services=$cfg_services_r
fi
cfg_services=${2:-$services}

# run the configured sequence
echo -n "Set pseudodate... "
  # System Datum setzen, zumindest auf was neuers,
  # als die Zeitstempel der compilierten Programme
  TIMEFILE=`find /* -type f -maxdepth 0 | xargs ls -1tr |tail -n1`
  STAT=`busybox stat -L -c %Y $TIMEFILE`
  date -s "1970-01-01 01:00:$STAT"
  
echo rcS start: `date +%T` > /var/log/startTime.txt

hostname $HOSTNAME

for i in $cfg_services
do
    if [ -x /etc/init.d/$i ]
    then                                                                        
        /etc/init.d/$i $mode
    fi                                                                          
done 

if [ $# -ge 2 ]
then 
    exit 0
fi

# show all kernel log messages
#echo 8 >  /proc/sys/kernel/printk

# run rc.local if present and executable
if [ -x /etc/rc.d/rc.local ]
then 
    /etc/rc.d/rc.local $mode
fi
echo rcS start ende: `date +%T` >> /var/log/startTime.txt