#!/bin/sh

if [ ! -x /sbin/devfsd ]
then
    exit 0
fi

if [ "$1" = "stop" -o "$1" = "restart" ]
then
    exit 0
fi

if [ "$1" = "start" -o "$1" = "restart" ]
then
    echo "Starting devfsd: "
    /sbin/devfsd /dev
fi

