INITRAMFS:= initramfs/
.PHONY: all
all: $(INITRAMFS)
	mkdir -p $(INITRAMFS)/dev/input $(INITRAMFS)/dev/net $(INITRAMFS)/dev/pts $(INITRAMFS)dev/shm $(INITRAMFS)etc/udhcpc $(INITRAMFS)/man $(INITRAMFS)/mnt $(INITRAMFS)/newroot $(INITRAMFS)/proc $(INITRAMFS)/sys $(INITRAMFS)/tmp $(INITRAMFS)/usr/mca $(INITRAMFS)/usr/work $(INITRAMFS)/var
