#!/bin/sh

if [ "$1" = "start" -o "$1" = "restart" ]
then
  echo -n "Insert mio driver module ... "
  insmod /fixsci.ko
  insmod /mio.ko
  echo "OK"

  echo -n "  - create FiFo's ... "
  mkfifo -m 666 /tmp/mdbg
  mkfifo -m 666 /tmp/mdvbi
  mkfifo -m 666 /tmp/mflt
  mkfifo -m 666 /tmp/mdesc
  echo "OK"

  echo -n "Set pseudodate... "
  # System Datum setzen, zumindest auf was neuers,
  # als die Zeitstempel der compilierten Programme
  OSCAM=/oscam
  STAT=`busybox stat -L -c %Y $OSCAM`
  date -s "1970-01-01 01:00:$STAT"
fi

