#!/bin/sh

if [ ! -x /usr/sbin/telnetd ]
then
    exit 0
fi

if [ "$1" = "stop" -o "$1" = "restart" ]
then                                                                            
    echo "Stopping the Telnet server: "
    killall telnetd
fi

if [ "$1" = "start" -o "$1" = "restart" ]                                       
then
    echo "Starting the Telnet server: "
    /usr/sbin/telnetd $TELNETD_ARGS
fi
