/*  
 *  src/include/buildConfig.h -- Build configuration file.
 *  
 *  WARNING: DO NOT EDIT. This file is generated by configure.
 *
 *  Use "./configure --help" for available options.
 */ 

    #define BLD_APPWEB_PRODUCT 1
    #define BLD_PRODUCT "appweb"
    #define BLD_NAME "Embedthis Appweb"
    #define BLD_VERSION "3.2.2"
    #define BLD_NUMBER "1"
    #define BLD_NUMBER_ONLY "1"
    #define BLD_MAJOR_VERSION 3
    #define BLD_MINOR_VERSION 2
    #define BLD_PATCH_VERSION 2
    #define BLD_VNUM "3002002"
    #define BLD_TYPE "RELEASE"
    #define BLD_TUNE MPR_TUNE_SIZE
    #define BLD_DEFAULTS "standard"
    #define BLD_COMPONENTS "     ar cc make nm strip ranlib doxygen regexp mpr ssl sqlite ejs appweb    "
    #define BLD_EMBEDTHIS 0

    #define BLD_COMPANY "Embedthis"
    #define BLD_DEBUG 0
    #define BLD_DIRS "build obj lib modules bin src test all doc samples projects package releases"
    #define BLD_CLEAN_INSTALL "0"
    #define BLD_LICENSE "gpl"
    #define BLD_COMMERCIAL "0"

    #define BLD_HOST_SYSTEM "arm-unknown-linux"
    #define BLD_BUILD_SYSTEM "i686-pc-linux"
    #define BLD_CROSS "1"

    #define BLD_HOST_OS "LINUX"
    #define BLD_HOST_CPU_ARCH MPR_CPU_ARM
    #define BLD_HOST_CPU "arm"
    #define BLD_HOST_CPU_UPPER "ARM"
    #define BLD_HOST_CPU_MODEL ""
    #define BLD_HOST_DIST "Unknown"
    #define BLD_HOST_DIST_VER "Unknown"
    #define BLD_HOST_UNIX 1
    #define BLD_HOST_WIN 0

    #define BLD_BUILD_OS "LINUX"
    #define BLD_BUILD_CPU_ARCH MPR_CPU_IX86
    #define BLD_BUILD_CPU "i686"
    #define BLD_BUILD_CPU_UPPER "I686"
    #define BLD_BUILD_CPU_MODEL "i686"
    #define BLD_BUILD_UNIX 1
    #define BLD_BUILD_WIN 0

    #define BLD_ROOT_PREFIX "/"
    #define BLD_PREFIX "/usr"
    #define BLD_CFG_PREFIX "/etc/appweb"
    #define BLD_BIN_PREFIX "/usr/lib/appweb/bin"
    #define BLD_DOC_PREFIX "/usr/lib/appweb/doc"
    #define BLD_INC_PREFIX "/usr/lib/appweb/inc"
    #define BLD_JEM_PREFIX "/usr/lib/appweb/jems"
    #define BLD_LIB_PREFIX "/usr/lib/appweb/lib"
    #define BLD_LOG_PREFIX "/var/log/appweb"
    #define BLD_MAN_PREFIX "/usr/lib/appweb/man"
    #define BLD_MOD_PREFIX "/usr/lib/appweb/modules"
    #define BLD_PRD_PREFIX "/usr/lib/appweb"
    #define BLD_SAM_PREFIX "/usr/lib/appweb/samples"
    #define BLD_SRC_PREFIX "/usr/src/appweb-3.2.2"
    #define BLD_VER_PREFIX "/usr/lib/appweb"
    #define BLD_WEB_PREFIX "/var/www/"

    #define BLD_BUILD_LIB_DIR "/home/asdf/Infocam_WebConf_v0.3/appweb/lib"
    #define BLD_BUILD_MOD_DIR "/home/asdf/Infocam_WebConf_v0.3/appweb/modules"

    #define BLD_FEATURE_ASSERT 0
    #define BLD_FEATURE_CMD 1
    #define BLD_FEATURE_COMPLETE_NATIVE 0
    #define BLD_FEATURE_COMPLETE_CROSS 1
    #define BLD_FEATURE_DOC 0
    #define BLD_FEATURE_DEVICE 
    #define BLD_FEATURE_FLOATING_POINT 0
    #define BLD_FEATURE_LEGACY_API 0
    #define BLD_FEATURE_MULTITHREAD 0
    #define BLD_FEATURE_NUM_TYPE int
    #define BLD_FEATURE_NUM_TYPE_STRING "int"
    #define BLD_FEATURE_SAMPLES 0
    #define BLD_FEATURE_TEST 0
    #define BLD_FEATURE_VMALLOC 1

    #ifdef STATIC_OVERRIDE
    #define         BLD_FEATURE_STATIC STATIC_OVERRIDE
    #else
    #define         BLD_FEATURE_STATIC 1
    #endif

    #define BLD_FEATURE_ACCESS_LOG 1
    #define BLD_FEATURE_ANGEL 0
    #define BLD_FEATURE_AUTH_DIGEST 0
    #define BLD_FEATURE_AUTH 1
    #define BLD_FEATURE_AUTH_FILE 1
    #define BLD_FEATURE_AUTH_PAM 0
    #define BLD_FEATURE_CGI 0
    #define BLD_FEATURE_CHUNK 1
    #define BLD_FEATURE_DIR 0
    #define BLD_FEATURE_EJS_ALL_IN_ONE 1
    #define BLD_FEATURE_EJS_AUTO_COMPILE 1
    #define BLD_FEATURE_EJS_CROSS_COMPILER 1
    #define BLD_FEATURE_EJS_DB 1
    #define BLD_FEATURE_EJS_DOC 0
    #define BLD_FEATURE_EJS_E4X 1
    #define BLD_FEATURE_EJS_LANG EJS_LANG_FIXED
    #define BLD_FEATURE_EJS_WEB 1
    #define BLD_FEATURE_EGI 0
    #define BLD_FEATURE_CONFIG template/standard
    #define BLD_FEATURE_CONFIG_PARSE 1
    #define BLD_FEATURE_FILE 1
    #define BLD_FEATURE_HTTP 1
    #define BLD_FEATURE_HTTP_CLIENT 0
    #define BLD_FEATURE_LOG 1
    #define BLD_FEATURE_NET 1
    #define BLD_FEATURE_NUM_TYPE_DOUBLE 0
    #define BLD_FEATURE_RANGE 1
    #define BLD_FEATURE_RUN_AS_SERVICE 1
    #define BLD_FEATURE_SEND 1
    #define BLD_FEATURE_UPLOAD 1
    #define BLD_FEATURE_XML 1

    #define BLD_HTTP_PORT 80
    #define BLD_SSL_PORT 4443


    #define BLD_BUILD_ARCH ".a"
    #define BLD_BUILD_EXE ""
    #define BLD_BUILD_OBJ ".o"
    #define BLD_BUILD_PIOBJ ".o"
    #define BLD_BUILD_CLASS ".class"
    #define BLD_BUILD_SHLIB ".so"
    #define BLD_BUILD_SHOBJ ".so"
    #define BLD_HOST_ARCH ".a"
    #define BLD_HOST_EXE ""
    #define BLD_HOST_OBJ ".o"
    #define BLD_HOST_PIOBJ ".o"
    #define BLD_HOST_CLASS ".class"
    #define BLD_HOST_SHLIB ".so"
    #define BLD_HOST_SHOBJ ".so"

#if !BUILDING_CROSS

    #

    #define 	BUILD_NATIVE_OR_COMPLETE_CROSS 1
    #define 	BUILD_CROSS_OR_COMPLETE_NATIVE 1

    #define 	LINUX 1
    #define 	BLD_OS "LINUX"
    #define 	BLD_CPU_ARCH MPR_CPU_IX86
    #define 	BLD_CPU "i686"
    #define 	BLD_CPU_UPPER "I686"
    #define 	BLD_CPU_MODEL "i686"
    #define 	BLD_DIST "ubuntu"
    #define 	BLD_DIST_VER "10.04"
    #define 	BLD_UNIX_LIKE 1
    #define 	BLD_WIN_LIKE 0

    #define 	BLD_CFLAGS ""
    #define 	BLD_DFLAGS ""
    #define 	BLD_IFLAGS ""
    #define 	BLD_LDFLAGS ""
    #define 	BLD_JFLAGS ""
    #define 	BLD_CPPFLAGS ""

    #define 	BLD_ARCH ".a"
    #define 	BLD_EXE ""
    #define 	BLD_CLASS ".class"
    #define 	BLD_SHLIB ".so"
    #define 	BLD_SHOBJ ".so"
    #define 	BLD_LIB ".a"
    #define 	BLD_OBJ ".o"
    #define 	BLD_PIOBJ ".o"

    #define     BLD_BIN_NAME "bin"
    #define     BLD_LIB_NAME "lib"
    #define     BLD_OBJ_NAME "obj"
    #define     BLD_MOD_NAME "modules"
    #define     BLD_INC_NAME "src/include"
    #define 	BLD_TOOLS_DIR "${BLD_TOP}/build/bin"
    #define 	BLD_BIN_DIR ${BLD_TOP}/bin
    #define 	BLD_OBJ_DIR ${BLD_TOP}/obj
    #define 	BLD_MOD_DIR ${BLD_TOP}/modules
    #define 	BLD_JEM_DIR ${BLD_TOP}/jlocal
    #define 	BLD_LIB_DIR ${BLD_TOP}/lib
    #define 	BLD_INC_DIR ${BLD_TOP}/src/include
    #define 	BLD_ABS_BIN_DIR "/home/asdf/Infocam_WebConf_v0.3/appweb/bin"
    #define 	BLD_ABS_LIB_DIR "/home/asdf/Infocam_WebConf_v0.3/appweb/lib"
    #define 	BLD_ABS_OBJ_DIR "/home/asdf/Infocam_WebConf_v0.3/appweb/obj"
    #define 	BLD_ABS_MOD_DIR "/home/asdf/Infocam_WebConf_v0.3/appweb/modules"
    #define 	BLD_ABS_JEM_DIR "/home/asdf/Infocam_WebConf_v0.3/appweb/jlocal"
    #define 	BLD_ABS_INC_DIR "/home/asdf/Infocam_WebConf_v0.3/appweb/src/include"

    #define     BLD_FEATURE_ROMFS 0

    #define 	BLD_FEATURE_AR 1
    #define 	BLD_AR "/usr/bin/ar"
    #define 	BLD_AR_BUILTIN 0
    #define 	BLD_AR_WITH "1"

    #define 	BLD_FEATURE_CC 1
    #define 	BLD_CC "/usr/bin/cc"
    #define 	BLD_CC_BUILTIN 0
    #define 	BLD_CC_WITH "1"
    #define 	BLD_CC_CYGWIN 0
    #define 	BLD_CC_DIAB 0
    #define 	BLD_CC_DOUBLE_BRACES 0
    #define 	BLD_CC_DYN_LOAD 1
    #define 	BLD_CC_MTUNE 1
    #define 	BLD_CC_MMU 1
    #define 	BLD_CC_WARN_UNUSED 1
    #define 	BLD_CC_EDITLINE 0
    #define 	BLD_CC_STACK_PROTECTOR 1

    #define 	BLD_FEATURE_MAKE 1
    #define 	BLD_MAKE "/usr/bin/make"
    #define 	BLD_MAKE_BUILTIN 0
    #define 	BLD_MAKE_WITH "1"

    #define 	BLD_FEATURE_NM 1
    #define 	BLD_NM "/usr/bin/nm"
    #define 	BLD_NM_BUILTIN 0
    #define 	BLD_NM_WITH "1"

    #define 	BLD_FEATURE_STRIP 1
    #define 	BLD_STRIP "/usr/bin/strip"
    #define 	BLD_STRIP_BUILTIN 0
    #define 	BLD_STRIP_WITH "1"

    #define 	BLD_FEATURE_RANLIB 1
    #define 	BLD_RANLIB "/usr/bin/ranlib"
    #define 	BLD_RANLIB_BUILTIN 0
    #define 	BLD_RANLIB_WITH "1"

    #define 	BLD_FEATURE_DOXYGEN 0

    #define 	BLD_FEATURE_REGEXP 1
    #define 	BLD_REGEXP "src/mpr/mprPcre.c"
    #define 	BLD_REGEXP_BUILTIN 1
    #define 	BLD_REGEXP_LIBS "pcre"
    #define 	BLD_REGEXP_WITH "1"

    #define 	BLD_FEATURE_MPR 1
    #define 	BLD_MPR "src/mpr"
    #define 	BLD_MPR_BUILTIN 1
    #define 	BLD_MPR_LIBS "mpr"
    #define 	BLD_MPR_WITH "1"

    #define 	BLD_FEATURE_SSL 0

    #define 	BLD_FEATURE_SQLITE 1
    #define 	BLD_SQLITE "/home/asdf/Infocam_WebConf_v0.3/appweb/src/ejs"
    #define 	BLD_SQLITE_BUILTIN 1
    #define 	BLD_SQLITE_DEPENDENCIES "mpr"
    #define 	BLD_SQLITE_LIBS "sqlite3 mpr"
    #define 	BLD_SQLITE_WITH "1"

    #define 	BLD_FEATURE_EJS 1
    #define 	BLD_EJS "/home/asdf/Infocam_WebConf_v0.3/appweb/src/ejs"
    #define 	BLD_EJS_BUILTIN 1
    #define 	BLD_EJS_DEPENDENCIES "mpr"
    #define 	BLD_EJS_LIBS "ajs pcre sqlite3 mpr mpr"
    #define 	BLD_EJS_OPTIONAL_DEPENDENCIES "ssl sqlite"
    #define 	BLD_EJS_WITH "1"
    #define 	BLD_EJS_WITHLIBS "pcre"

    #define 	BLD_FEATURE_APPWEB 1
    #define 	BLD_APPWEB "/home/asdf/Infocam_WebConf_v0.3/appweb/src/server"
    #define 	BLD_APPWEB_BUILTIN 1
    #define 	BLD_APPWEB_DEPENDENCIES "mpr"
    #define 	BLD_APPWEB_IFLAGS "-I/home/asdf/Infocam_WebConf_v0.3/appweb/src/server/include"
    #define 	BLD_APPWEB_LIBS "appweb ejs ajs pcre sqlite3 mpr mpr mpr"
    #define 	BLD_APPWEB_OPTIONAL_DEPENDENCIES "ssl ejs"
    #define 	BLD_APPWEB_WITH "1"

    #define 	BLD_FEATURE_MATRIXSSL 0
    #define 	BLD_FEATURE_MYSQL 0
    #define 	BLD_FEATURE_OPENSSL 0
    #define 	BLD_FEATURE_PHP 0


#else

    #

    #define 	BUILD_NATIVE_OR_COMPLETE_CROSS 1
    #define 	BUILD_CROSS_OR_COMPLETE_NATIVE 1

    #define 	LINUX 1
    #define 	BLD_OS "LINUX"
    #define 	BLD_CPU_ARCH MPR_CPU_ARM
    #define 	BLD_CPU "arm"
    #define 	BLD_CPU_UPPER "ARM"
    #define 	BLD_CPU_MODEL ""
    #define 	BLD_DIST "Unknown"
    #define 	BLD_DIST_VER "Unknown"
    #define 	BLD_UNIX_LIKE 1
    #define 	BLD_WIN_LIKE 0

    #define 	BLD_CFLAGS ""
    #define 	BLD_DFLAGS ""
    #define 	BLD_IFLAGS ""
    #define 	BLD_LDFLAGS ""
    #define 	BLD_JFLAGS ""
    #define 	BLD_CPPFLAGS ""

    #define 	BLD_ARCH ".a"
    #define 	BLD_EXE ""
    #define 	BLD_CLASS ".class"
    #define 	BLD_SHLIB ".so"
    #define 	BLD_SHOBJ ".so"
    #define 	BLD_LIB ".a"
    #define 	BLD_OBJ ".o"
    #define 	BLD_PIOBJ ".o"

    #define     BLD_BIN_NAME "bin/arm-unknown-linux"
    #define     BLD_LIB_NAME "lib/arm-unknown-linux"
    #define     BLD_OBJ_NAME "obj/arm-unknown-linux"
    #define     BLD_MOD_NAME "modules/arm-unknown-linux"
    #define     BLD_INC_NAME "src/include"
    #define 	BLD_TOOLS_DIR "${BLD_TOP}/build/bin"
    #define 	BLD_BIN_DIR ${BLD_TOP}/bin/arm-unknown-linux
    #define 	BLD_OBJ_DIR ${BLD_TOP}/obj/arm-unknown-linux
    #define 	BLD_MOD_DIR ${BLD_TOP}/modules/arm-unknown-linux
    #define 	BLD_JEM_DIR ${BLD_TOP}/jlocal/arm-unknown-linux
    #define 	BLD_LIB_DIR ${BLD_TOP}/lib/arm-unknown-linux
    #define 	BLD_INC_DIR ${BLD_TOP}/src/include
    #define 	BLD_ABS_BIN_DIR "/home/asdf/Infocam_WebConf_v0.3/appweb/bin/arm-unknown-linux"
    #define 	BLD_ABS_LIB_DIR "/home/asdf/Infocam_WebConf_v0.3/appweb/lib/arm-unknown-linux"
    #define 	BLD_ABS_OBJ_DIR "/home/asdf/Infocam_WebConf_v0.3/appweb/obj/arm-unknown-linux"
    #define 	BLD_ABS_MOD_DIR "/home/asdf/Infocam_WebConf_v0.3/appweb/modules/arm-unknown-linux"
    #define 	BLD_ABS_JEM_DIR "/home/asdf/Infocam_WebConf_v0.3/appweb/jlocal/arm-unknown-linux"
    #define 	BLD_ABS_INC_DIR "/home/asdf/Infocam_WebConf_v0.3/appweb/src/include"

    #define     BLD_FEATURE_ROMFS 0

    #define 	BLD_FEATURE_AR 1
    #define 	BLD_AR "/home/asdf/prj/lpc313x/eldk42/usr/bin/arm-linux-ar"
    #define 	BLD_AR_BUILTIN 0
    #define 	BLD_AR_WITH "1"

    #define 	BLD_FEATURE_CC 1
    #define 	BLD_CC "/home/asdf/prj/lpc313x/eldk42/usr/bin/arm-linux-gcc"
    #define 	BLD_CC_BUILTIN 0
    #define 	BLD_CC_WITH "1"
    #define 	BLD_CC_CYGWIN 0
    #define 	BLD_CC_DIAB 0
    #define 	BLD_CC_DOUBLE_BRACES 0
    #define 	BLD_CC_DYN_LOAD 1
    #define 	BLD_CC_MTUNE 0
    #define 	BLD_CC_MMU 1
    #define 	BLD_CC_WARN_UNUSED 0
    #define 	BLD_CC_EDITLINE 0
    #define 	BLD_CC_STACK_PROTECTOR 1

    #define 	BLD_FEATURE_MAKE 1
    #define 	BLD_MAKE "/usr/bin/make"
    #define 	BLD_MAKE_BUILTIN 0
    #define 	BLD_MAKE_WITH "1"

    #define 	BLD_FEATURE_NM 1
    #define 	BLD_NM "/home/asdf/prj/lpc313x/eldk42/usr/bin/arm-linux-nm"
    #define 	BLD_NM_BUILTIN 0
    #define 	BLD_NM_WITH "1"

    #define 	BLD_FEATURE_STRIP 1
    #define 	BLD_STRIP "/home/asdf/prj/lpc313x/eldk42/usr/bin/arm-linux-strip"
    #define 	BLD_STRIP_BUILTIN 0
    #define 	BLD_STRIP_WITH "1"

    #define 	BLD_FEATURE_RANLIB 1
    #define 	BLD_RANLIB "/home/asdf/prj/lpc313x/eldk42/usr/bin/arm-linux-ranlib"
    #define 	BLD_RANLIB_BUILTIN 0
    #define 	BLD_RANLIB_WITH "1"

    #define 	BLD_FEATURE_DOXYGEN 0

    #define 	BLD_FEATURE_REGEXP 1
    #define 	BLD_REGEXP "src/mpr/mprPcre.c"
    #define 	BLD_REGEXP_BUILTIN 1
    #define 	BLD_REGEXP_LIBS "pcre"
    #define 	BLD_REGEXP_WITH "1"

    #define 	BLD_FEATURE_MPR 1
    #define 	BLD_MPR "src/mpr"
    #define 	BLD_MPR_BUILTIN 1
    #define 	BLD_MPR_LIBS "mpr"
    #define 	BLD_MPR_WITH "1"

    #define 	BLD_FEATURE_SSL 0

    #define 	BLD_FEATURE_SQLITE 1
    #define 	BLD_SQLITE "/home/asdf/Infocam_WebConf_v0.3/appweb/src/ejs"
    #define 	BLD_SQLITE_BUILTIN 1
    #define 	BLD_SQLITE_DEPENDENCIES "mpr"
    #define 	BLD_SQLITE_LIBS "sqlite3 mpr"
    #define 	BLD_SQLITE_WITH "1"

    #define 	BLD_FEATURE_EJS 1
    #define 	BLD_EJS "/home/asdf/Infocam_WebConf_v0.3/appweb/src/ejs"
    #define 	BLD_EJS_BUILTIN 1
    #define 	BLD_EJS_DEPENDENCIES "mpr"
    #define 	BLD_EJS_LIBS "ajs pcre sqlite3 mpr mpr"
    #define 	BLD_EJS_OPTIONAL_DEPENDENCIES "ssl sqlite"
    #define 	BLD_EJS_WITH "1"
    #define 	BLD_EJS_WITHLIBS "pcre pcre"

    #define 	BLD_FEATURE_APPWEB 1
    #define 	BLD_APPWEB "/home/asdf/Infocam_WebConf_v0.3/appweb/src/server"
    #define 	BLD_APPWEB_BUILTIN 1
    #define 	BLD_APPWEB_DEPENDENCIES "mpr"
    #define 	BLD_APPWEB_IFLAGS "-I/home/asdf/Infocam_WebConf_v0.3/appweb/src/server/include"
    #define 	BLD_APPWEB_LIBS "appweb ejs ajs pcre sqlite3 mpr mpr mpr"
    #define 	BLD_APPWEB_OPTIONAL_DEPENDENCIES "ssl ejs"
    #define 	BLD_APPWEB_WITH "1"

    #define 	BLD_FEATURE_MATRIXSSL 0
    #define 	BLD_FEATURE_MYSQL 0
    #define 	BLD_FEATURE_OPENSSL 0
    #define 	BLD_FEATURE_PHP 0

#endif
